Integration test to verify the model's expected result for 1D and 2D base cases
openearth/aeolis-python pull request #105
Opened 2023-03-21 12:48 UTC by niketagrawal

- The model is expected to produce the same output for the same input; this high-level test checks if the output of the model has changed for the same input. Such a test would help detect if some of the model's core functionalities are broken due to any incoming new code changes. This would be made possible by making this test run automatically on every push to the repository via the use of GitHub actions. This will be enabled in the repository after these code changes are merged to main.
- Checking for continuity/mass conservation would be relevant test case to add to the list of the test cases, but its development is not yet completed.
- Closes #60

2023-03-29 10:04 UTC, manuGil requested changes

2023-03-29 10:04 UTC, manuGil commented on aeolis/tests/integration_tests/test_integration.py
Test for 2D examples failed with the following:
```shell
FAILED aeolis/tests/integration_tests/test_integration.py::test_integration - 
AssertionError: Array values of the parameter 'time' are expected to remain consistent 
across simulations for the same model parameter file for 2D Barchan_dune
```

2023-04-05 07:40 UTC, niketagrawal commented on aeolis/tests/integration_tests/test_integration.py
Thanks for reporting the bug. The new code changes should fix it. Can you please rerun the test?

The bug is caused by using the numpy array compare functions for comparing two masked arrays. Unmasking the arrays converts them to regular numpy arrays, which are compatible with element-wise comparisons of numpy.allclose.

2023-04-05 08:53 UTC, manuGil commented on aeolis/tests/integration_tests/test_integration.py
All tests passed now.

2023-04-05 09:02 UTC, manuGil approved these changes

2023-04-05 12:43 UTC, merged