Implementing TOML file for packaging
openearth/aeolis-python pull request #125
Opened 2023-06-21 14:10 UTC by manuGil

- Implement pyproject.toml
- Change build-system from setuptools to hatchling
- Remove docs/ and test/ directories from source disbtirution
- Update Readme.md Release.md and Contiguting.md
- Modified model.py for fetching version from package metadata

Closes #107 
Fixes #36

2023-06-27 15:12 UTC, niketagrawal requested changes
Thanks for adding the changes. 

The publish-workflow.yml needs to be modified because the names of the source and wheel distributions created with the pyproject and hatchling based build system are different than the ones created by the existing setup.py based build system.

The names of the source and wheel distributions created by the `python -m build` command with these changes 
are `aeolis-2.1.1-py3-none-any.whl` and `aeolis-2.1.1.tar.gz`, however, [the publish-workflow.yml in main searches for the pattern AeoLiS-*.whl during installation test](https://github.com/openearth/aeolis-python/blob/a520985fb66e10a58ad3e1c5eec51722c05ae79c/.github/workflows/publish-release.yml#L39)

Can you please update the publish-workflow.yml as part of these changes?

2023-06-27 15:12 UTC, niketagrawal commented on CONTRIBUTING.md
> +    pip install -e .[dev]
Remove `-e` in the absence of setup.py.

`pip install .[dev]` is the correct command as mentioned in your changes to the README.md file.

2023-06-28 08:57 UTC, manuGil commented on CONTRIBUTING.md
> +    pip install -e .[dev]
> Remove `-e` in the absence of setup.py.
> 
> `pip install .[dev]` is the correct command as mentioned in your changes to the README.md file.

`pip install -e .[dev] works for me, while in the root directory of the repo (where the `pyproject.toml`) is located. Can you try one more time, please?

2023-06-28 11:22 UTC, niketagrawal commented on CONTRIBUTING.md
> +    pip install -e .[dev]
Thank you for the hint to update pip.
The command `pip install -e .[dev]` works after updating pip to the latest version (23.1.2).

2023-06-28 11:24 UTC, niketagrawal approved these changes

2023-06-28 12:22 UTC, manuGil commented
@niketagrawal I completed the changes. I will merge this PR

2023-06-28 12:25 UTC, merged