Major update V3
openearth/aeolis-python pull request #181
Opened 2024-03-11 10:11 UTC by Sierd

Solver, vegetation, Landforms

2024-03-14 11:55 UTC, niketagrawal requested changes
The path to the aeolis.txt file and the callback function used by the test function is incorrect.

2024-03-14 11:55 UTC, niketagrawal commented on aeolis/tests/test_model.py
> +        runner = AeoLiSRunner("aeolis.txt")
This path to aeolis.txt file is incorrect. The correct path is "aeolis/test/aeolis.txt"

2024-03-14 11:55 UTC, niketagrawal commented on aeolis/tests/test_model.py
> +        callback = runner.parse_callback("callback_example.py:mock_callback")
This path to the callback function is incorrect. The correct path is "aeolis/tests/callback_example.py:mock_callback"

2024-07-21 23:04 UTC, Sierd commented
rushed pre-release to kickstart 2024 sprint session

2024-07-21 23:05 UTC, merged